language: c
arch:
  - arm64
    addons:
      apt:
        packages:
          - python3
          - gcc-arm-linux-gnueabihf
  - amd64
    addons:
      apt:
        packages:
          - python3
os: linux
dist: focal

compiler:
    - gcc

      #Build steps
before_script:
    - mkdir build
    - cd build
    - if [ "$TRAVIS_CPU_ARCH" = "arm64" ]; then 
    - cmake .. -DRK3399=1 -DCMAKE_BUILD_TYPE=RelWithDebInfo
    - else
    - CFLAGS="-m32" cmake .. -DLD80BITS=1 -DNOALIGN=1 -DCMAKE_BUILD_TYPE=RelWithDebInfo
    - fi

script:
    - make
    - ctest --output-on-failure